accountapp/urls.py
from django.urls import path

from accountapp.views import helloworld
from accountapp.views import AccountCreateView

#브라우저에서 
app_name='accountapp'

urlpatterns=[
    #path(route,view,name=)
    path('helloworld/',helloworld,name='helloworld'),
    path('create/',AccountCreateView.as_view(),name='create'),
]

pinterest/urls.py
from django.contrib import admin
from django.urls import include, path
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accountapp.urls')),
]

accountapp/models.py
from django.db import models

# Create your models here.
class Helloworld(models.Model):
    text=models.CharField(max_length=255, null=False)
    

accountapp/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from accountapp.models import Helloworld
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def helloworld(request):
    #HttpResponse:view에서 응답을 직접 만들어서 웹으로 넘겨주는 방식
    #render:templates애 있는 Html파일에 값이 들어갈 수 있도록 하는 기능
    # return render(request,'accountapp/helloworld.html')

    if request.method=="POST":
        temp=request.POST.get('helloworld_input') #request>POST>name이 helloworld_input인 데이터를 가져오라는 명령어
        
        #모델 객체 생성 및 데이터 DB저장
        new_Helloworld=Helloworld()
        new_Helloworld.text=temp
        new_Helloworld.save()

        #모든 데이터 다 가져오기
        helloworld_list=Helloworld.objects.all()

        # return render(request,'accountapp/helloworld.html',context={'helloworld_list':helloworld_list})
        return HttpResponseRedirect(reverse('accountapp:helloworld'))
    else:
        # helloworld_list=Helloworld.objects.all()
        return render(request,'accountapp/helloworld.html',context={'helloworld_list':helloworld_list})

class AccountCreateView(CreateView):
    model=User
    form_class= UserCreationForm
    #계정생성에 성공했을 경우 어느 경로로 다시 연결할건지 설정
    success_url=reverse_lazy('accountapp:helloworld')
    #회원가입 화면 html 지정
    template_name='accountapp/create.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% block content %}

<div style="text-align: center;">
    <form action="{% url 'accountapp:create' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" name="btn btn-primary">
    </form>

</div>
{% endblock %}

accountapp/templates/accountapp/helloworld.html
{% extends 'base.html'%}

{% block content %}

<style>
    .testing {
        background-color: white;
        height:3rem;
        width:3rem;
        margin:1rem;
    }
</style>

<div style="border-radius:1rem; margin:2rem; text-align:center;">
    <h1 style="font-family: 'Playfair Display', serif;">
        Helloworld list!
    </h1>

    <form action="/account/helloworld/" method="post">
        {% csrf_token %}
        <div>
            <input type="text" name="helloworld_input">
        </div>
        <div>
            <input type="submit" class="btn btn-primary" value="POST">

        </div>

    </form>
    {% if helloworld_list %}
        {% for hello_world in helloworld_list %}
        <h4>
            {{hello_world.text}}
        </h4>
        {% endfor %}
    {% endif %}


</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include 'head.html' %}


<body>
    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}
    
    <hr>
    {% include 'footer.html'  %}
</body>
</html>

templates/footer.html
<div class="pragmatic_footer">
    <div class="pragmatic_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스소개</span>

    </div>
    <div style="margin-top:1rem">
        <h6 class="pragmatic_logo">pragmatic</h6>
    </div>

</div>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>이선희의 장고프로젝트</title>

    <!--bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <!-- Google font link -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    
    <!-- Default css link -->
    <link rel="stylesheet" type="text/css" href = "{% static 'base.css' %}">

</head>

templates/header.html
<div style="text-align: center; margin: 2rem 0; font-family: 'Noto Sans KR'">
   <div>
    <h1 class="pragmatic_logo">pragmatic</h1>
   </div>
   <div>
    <span>nav1</span>
    <span>nav2</span>
    <span>nav3</span>
    <span>nav4</span>
   </div>


</div> 